export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const Place_Order = "Place_Order";
export const Add_Qty = "Add_qty";
export const Remove_Qty = "Remove_qty";
export const Fetch_Db ="Fetch_db"
export const Set_Title = "SetTitle"